### ISSUE TITLE
求个原视频

### ISSUE THREAD

**Issue by mrnuclear8** [lih627/MLMSNet#1]
大佬你好，我看了你的bilibili视频《Mobilenet 分割 Cityscapes Demo》，你那里还有这个视频的原视频吗，不跑语义分割网络的，我的模型需要一个Cityscapes的视频推理，但是Cityscapes数据集太大了，暂时下不下来，急用，能发我一份原视频吗，视频已投币，谢谢
，我的邮箱littlefingerpy@163.com

**Comment by lih627** [comment]
抱歉 这个很久了我也没有原始视频存档了…

发自我的iPhone

在 2022年5月15日，22:08，mrnuclear8 ***@***.***> 写道：

﻿

大佬你好，我看了你的bilibili视频《Mobilenet 分割 Cityscapes Demo》，你那里还有这个视频的原视频吗，不跑语义分割网络的，我的模型需要一个Cityscapes的视频推理，但是Cityscapes数据集太大了，暂时下不下来，急用，能发我一份原视频吗，视频已投币，谢谢
***@***.******@***.***>
